eureka.client.fetch-registry=true

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Prefer IP address instead of hostname
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
